-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-05-02 01:55:50 CEST
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g




CREATE TABLE friend
  (
    player_id INTEGER NOT NULL ,
    friend_id INTEGER NOT NULL
  ) ;
CREATE INDEX friend__IDX ON friend
  ( player_id ASC
  ) ;
ALTER TABLE friend ADD CONSTRAINT friend_PK PRIMARY KEY ( player_id, friend_id ) ;


CREATE TABLE game
  (
    game_id    INTEGER NOT NULL ,
    begin_time TIMESTAMP NOT NULL ,
    end_time   TIMESTAMP NOT NULL ,
    game_log CLOB
  ) ;
CREATE UNIQUE INDEX game__IDX ON game
  (
    game_id ASC
  )
  ;
ALTER TABLE game ADD CONSTRAINT game_PK PRIMARY KEY ( game_id ) ;


CREATE TABLE player
  ( player_id INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX player__IDX ON player
  (
    player_id ASC
  )
  ;
ALTER TABLE player ADD CONSTRAINT player_PK PRIMARY KEY ( player_id ) ;


CREATE TABLE player_profile
  (
    login VARCHAR2 (25) NOT NULL ,
    password_hash BLOB NOT NULL ,
    nick          VARCHAR2 (50) NOT NULL ,
    "e-mail"      VARCHAR2 (100) NOT NULL ,
    register_data TIMESTAMP NOT NULL ,
    last_act_data TIMESTAMP NOT NULL ,
    player_id     INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX player_profile__IDX ON player_profile
  (
    player_id ASC
  )
  ;
CREATE UNIQUE INDEX player_profile__IDX_login ON player_profile
  (
    login ASC
  )
  ;
CREATE UNIQUE INDEX "player_profile__IDX_e-mail" ON player_profile
  (
    "e-mail" ASC
  )
  ;
ALTER TABLE player_profile ADD CONSTRAINT pp_PK PRIMARY KEY ( player_id ) ;
ALTER TABLE player_profile ADD CONSTRAINT player_profile__UN_login UNIQUE ( login ) ;
ALTER TABLE player_profile ADD CONSTRAINT "player_profile__UN_e-mail" UNIQUE ( "e-mail" ) ;


CREATE TABLE score
  (
    walkover         CHAR (1) NOT NULL ,
    place            INTEGER NOT NULL ,
    score            INTEGER NOT NULL ,
    player_player_id INTEGER NOT NULL ,
    game_game_id     INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX score__IDX ON score
  (
    player_player_id ASC , game_game_id ASC
  )
  ;
  CREATE INDEX score__IDX_player ON score
    ( player_player_id ASC
    ) ;
  CREATE INDEX score__IDX_game ON score
    ( game_game_id ASC
    ) ;
ALTER TABLE score ADD CONSTRAINT score_PK PRIMARY KEY ( player_player_id, game_game_id ) ;


ALTER TABLE friend ADD CONSTRAINT FK_ASS_2 FOREIGN KEY ( player_id ) REFERENCES player_profile ( player_id ) ;

ALTER TABLE friend ADD CONSTRAINT FK_ASS_3 FOREIGN KEY ( friend_id ) REFERENCES player_profile ( player_id ) ;

ALTER TABLE player_profile ADD CONSTRAINT player_profile_player_FK FOREIGN KEY ( player_id ) REFERENCES player ( player_id ) ;

ALTER TABLE score ADD CONSTRAINT score_game_FK FOREIGN KEY ( game_game_id ) REFERENCES game ( game_id ) ;

ALTER TABLE score ADD CONSTRAINT score_player_FK FOREIGN KEY ( player_player_id ) REFERENCES player ( player_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             9
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
