//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyCrab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyCrab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja SkyCrab powstała w wyniku realizacji projektu na przedmiot Projekt Zespołowy. Twórcy gry nie pobierają za nią żadnych opłat.
        ///
        ///Jej autorami są: Krzysztof Jerzyński - twórca aplikacji klienta gry oraz Piotr Siupa - twórca aplikacji serwera gry
        ///
        ///W kwestii dotyczących pomysłów rozwoju niniejszej aplikacji prosimy o kontakt podany poniżej.
        ///
        ///Kontakt e-mail:  krzysztof.k.jerzynski@student.put.poznan.pl 
        ///					       piotr.siupa@student.put.poznan.pl
        ///
        ///Dziękujemy za skorzystanie z naszej aplikacji. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Zabronione jest obrażanie innych członków społeczności gry. Wyjątkiem jest określenie &quot;noob&quot;. Drugim wyjątkiem jest chat w grze, gdzie kwestia obraz i pozwolenia na ich używanie należy do twórcy/właściciela i moderatorów danego chatroomu.
        ///2) Zabronione jest używanie wulgaryzmów (również wykropkowanych, przekręconych itp. oraz będącymi wulgaryzmami w językach obcych). Drugim wyjątkiem jest chat w grze, gdzie kwestia wulgaryzmów i pozwolenia na ich używanie należy do twórcy/właściciela i moderatorów daneg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RulesText {
            get {
                return ResourceManager.GetString("RulesText", resourceCulture);
            }
        }
    }
}
